pool:
  vmImage: 'ubuntu-16.04'

variables:
  image: 'tablevisualization'
  latestTag: '$(image):latest'

steps:

- script: |
    docker build -f Dockerfile-Azure -t $(dockerId).azurecr.io/$(latestTag) .
    docker login -u $(dockerId) -p $(pswd) $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(latestTag)
  displayName: 'Build and push Docker image'