version: "3"

services:
    postgresql:  
        image: postgres:10.5
        hostname: postgresql          
        container_name: postgresql
        restart: always
        environment:                                                            
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dbpw
            - POSTGRES_DB=mydb
        ports:
            - "5432:5432"

    app:
        build: .
        hostname: app
        restart: always
        environment:
            - POSTGRES_URL=postgresql:5432
            - POSTGRES_USER=postgres
            - POSTGRES_PW=dbpw
            - POSTGRES_DB=mydb
            - APP_SETTINGS=config.DevelopmentConfig
            - APP_KEY=random
        container_name: app
        ports:
            - "4000:80"
        volumes:
            - .:/app
        depends_on:
            - postgresql


